trigger:
- master

strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
    linux-beta:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: beta
    linux-nightly:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: true
  - script: |
      sudo apt-get install -y build-essential libgcrypt20-dev cmake clang flex bison
    displayName: apt install dependencies
    condition: eq( variables['Agent.OS'], 'Linux')
  - script: |
      brew install glib libgcrypt pkg-config flex bison
    displayName: brew install dependencies
    condition: eq( variables['Agent.OS'], 'Darwin')
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git
      .\vcpkg\bootstrap-vcpkg.bat
      .\vcpkg\vcpkg.exe install glib
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: vcpkg install dependencies
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      echo "##vso[task.setvariable variable=PLATFORM;]win64"
      echo "##vso[task.setvariable variable=WIRESHARK_BASE_DIR;]C:/wireshark-libs"
    displayName: Windows set environment variables
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all --verbose
    displayName: Cargo build
  - script: cargo test --all --verbose
    displayName: Cargo test
